services:
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    _defaults:
        autowire: true
        autoconfigure: true

    Akyos\CanopeeAssets\:
        resource: './../../*'
        tags: [ 'controller.service_arguments' ]
        public: true
