services:
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    _defaults:
        autowire: true
        autoconfigure: true

    Akyos\CanopeeAssets\:
        resource: './../../*'
        exclude:
            - '../../DependencyInjection/'
            - '../../Class/'
        tags: [ 'controller.service_arguments' ]
        public: true
